version: '3'

services:
    mongoLAB01CdO5fL:
        image: poc2opslabs/lab01:latest
        container_name: Mongo-LAB01CdO5fL
#        environment:
#            - MONGO_INITDB_ROOT_USERNAME=lab01
#            - MONGO_INITDB_ROOT_PASSWORD=lab01
        restart: always    
        ports:
            - 57652:27017   
        #command: --serviceExecutor adaptive  
        networks: 
            - LAB01CdO5fL   
    mongo-expressLAB01CdO5fL:
        image: mongo-express
        container_name: MongoExpress-LAB01CdO5fL
        restart: always
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongoLAB01CdO5fL
            - ME_CONFIG_MONGODB_PORT=27017
#            - ME_CONFIG_MONGODB_ADMINUSERNAME=lab01
#            - ME_CONFIG_MONGODB_ADMINPASSWORD=lab01
        depends_on:
            - mongoLAB01CdO5fL
        ports:
            - "58534:8081"
        networks: 
            - LAB01CdO5fL   

networks:
  LAB01CdO5fL:
    driver: bridge 
    
#mongodb://127.0.0.1:27017/?readPreference=primary&gssapiServiceName=mongodb&appname=MongoDB%20Compass&ssl=false    